window.addEventListener("load",function(){function V(){W&&(ea(),fa(h("guide")),clearInterval(V))}function ha(){N++;273===N&&(W=!W);g.clearRect(0,0,p,q);g.beginPath();g.lineWidth=4;g.strokeStyle=A.color;g.stroke();g.strokeRect(A.x-g.lineWidth/2,A.y-g.lineWidth/2,A.g+g.lineWidth,A.f+g.lineWidth);g.fillStyle="rgb(255, 161, 0)";g.fillRect(A.x,A.y,N/273*A.g,A.f);g.fillStyle="rgb(255, 161, 0)";g.textAlign="center";g.font="normal 25px Verdana";g.fillText("\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430: "+
(100*N/273).toFixed(3)+"%",p/2,q/2+30+g.lineWidth);g.closePath()}function O(){for(var a=15*Math.random()+10^0,c="0123456789abcdef".split(""),n="#",d=1;6>=d;d++)n+=c[Math.random()*c.length^0];a=new ia(new m(r(arguments[0])?arguments[0]:Math.random()*p,r(arguments[1])?arguments[1]:Math.random()*q),a,n,new m(Math.random()*(P-F)+F,Math.random()*(Q-G)+G),a);arguments.length?b.push(a):b.push(ra(a))}function R(a,c){return Math.floor(Math.random()*(c-a))+a}function ra(a){for(var c=0;c<b.length;c++)a!==b[c]&&
B(a.position.x,a.position.y,b[c].position.x,b[c].position.y)<a.r+b[c].r&&(a.position.x=Math.random()*p,a.position.r=Math.random()*q);return a}function ia(a,c,b,d,e){this.position=a;this.r=c;this.color=b;this.b=d;this.l=e;this.c=new m(k.c.x,k.c.y);this.i=[u[0]];this.h=new m(k.h.x,k.h.y);this.o=k.o;this.A=!0;this.angle=0;this.B=!0;this.s=w[Math.random()*w.length^0]}function m(a,c){this.x=a;this.y=c}function x(a,c,b,f,e){this.x=a;this.y=c;this.g=b;this.f=f;this.s=e;this.ga=d.fa.checked;a=this.w={block:this,
C:function(a){if(!a.c.x&&0<a.c.y)return k.j({x:this.block.a[1].x,y:this.block.a[1].y-2,g:this.block.a[1].g,f:this.block.a[1].f},a);if(!a.c.x&&0>a.c.y)return k.j({x:this.block.a[4].x,y:this.block.a[4].y,g:this.block.a[4].g,f:this.block.a[4].f+2},a);if(0<a.c.x&&!a.c.y)return k.j({x:this.block.a[3].x-2,y:this.block.a[3].y,g:this.block.a[3].g,f:this.block.a[3].f},a);if(0>a.c.x&&!a.c.y)return k.j({x:this.block.a[5].x,y:this.block.a[5].y,g:this.block.a[5].g+2,f:this.block.a[5].f},a);if(0<a.c.x&&0<a.c.y)return k.j({x:this.block.a[1].x,
y:this.block.a[1].y-2,g:this.block.a[1].g,f:this.block.a[1].f},a)||k.j({x:this.block.a[3].x-2,y:this.block.a[3].y,g:this.block.a[3].g,f:this.block.a[3].f},a);if(0<a.c.x&&0>a.c.y)return k.j({x:this.block.a[4].x,y:this.block.a[4].y,g:this.block.a[4].g,f:this.block.a[4].f+2},a)||k.j({x:this.block.a[3].x-2,y:this.block.a[3].y,g:this.block.a[3].g,f:this.block.a[3].f},a);if(0>a.c.x&&0<a.c.y)return k.j({x:this.block.a[5].x,y:this.block.a[5].y,g:this.block.a[5].g+2,f:this.block.a[5].f},a)||k.j({x:this.block.a[1].x,
y:this.block.a[1].y-2,g:this.block.a[1].g,f:this.block.a[1].f},a);if(0>a.c.x&&0>a.c.y)return k.j({x:this.block.a[5].x,y:this.block.a[5].y,g:this.block.a[5].g+2,f:this.block.a[5].f},a)||k.j({x:this.block.a[4].x,y:this.block.a[4].y,g:this.block.a[4].g,f:this.block.a[4].f+2},a)}};a.C=a.C.bind(a);(x.i?x.i:[]).push(a)}function ta(a){return function(){var c=[r(+d.D.value)?w[+d.D.value]:b[f].s?b[f].s:w[Math.random()*w.length^0],r(parseFloat(d.r.value))?+d.r.value:100*Math.random()^0,r(parseFloat(d.l.value))?
+d.l.value:100*Math.random()^0,{m:r(parseFloat(d.x.value))?+d.x.value:Math.random()*p^0},{m:r(parseFloat(d.y.value))?+d.y.value:Math.random()*q^0},{m:r(parseFloat(d.T.value))?+d.T.value:20*Math.random()^0},{m:r(parseFloat(d.U.value))?+d.U.value:20*Math.random()^0},{m:r(+d.c.value.match(/[\d.-]+/)[0])?+d.c.value.match(/[\d.-]+/)[0]:k.c.x,S:r(+d.c.value.match(/[\d.-]+/g)[1])?+d.c.value.match(/[\d.-]+/g)[1]:k.c.y},{m:r(+d.h.value.match(/[\d.-]+/)[0])?+d.h.value.match(/[\d.-]+/)[0]:k.h.x,S:r(+d.h.value.match(/[\d.-]+/g)[1])?
+d.h.value.match(/[\d.-]+/g)[1]:k.h.y},r(parseFloat(d.o.value))?+d.o.value:k.o,new Function("",d.G.value)];if(arguments.length)for(var n=0;n<b.length;n++)ja(b[n],ka[a],c[a]);else ja(b[f],ka[a],c[a])}}function ja(a,c,b){if("string"===typeof c)a[c]=b;else for(var n in c)"fp"!=n&&(a[c.fp][c[n]]=b[n],"deceleration"===c.fp&&("sp"===n?k.h.x=b[n]:k.h.y=b[n]),"gravity"===c.fp&&("sp"===n?k.c.x=b[n]:k.c.y=b[n],la(a)))}function B(a,c,b,d){return Math.pow(Math.pow(a-b,2)+Math.pow(c-d,2),.5)}function h(a){return document.getElementById(a)}
function S(){d.Z.value=f;d.D.value=w.indexOf(b[f].s);d.r.value=+b[f].r.toFixed(3);d.l.value=+b[f].l.toFixed(3);d.x.value=+b[f].position.x.toFixed(3);d.y.value=+b[f].position.y.toFixed(3);d.T.value=+b[f].b.x.toFixed(3);d.U.value=+b[f].b.y.toFixed(3);d.c.value=b[f].c;d.h.value=b[f].h;d.o.value=b[f].o;d.V.value=v;d.H.value=H;d.J.value=I;d.I.value=J;d.Y.value=T;d.N.value=F;d.K.value=P;d.O.value=G;d.L.value=Q}function ua(){for(var a=1;a<U.length;a++)U[a].onclick();H=parseFloat(+d.H.value)?+d.H.value:H;
v=+d.V.value;I=parseFloat(+d.J.value)?d.J.value:I;J=parseFloat(+d.I.value)?d.I.value:J;F="number"==typeof parseFloat(+d.N.value)?+d.N.value:F;P="number"==typeof parseFloat(+d.K.value)?+d.K.value:P;G="number"==typeof parseFloat(+d.O.value)?+d.O.value:G;Q="number"==typeof parseFloat(+d.L.value)?+d.L.value:Q;if(v>b.length)for(a=b.length;a<v;a++)O();else v<b.length&&(b=b.slice(0,0>v?(v=0,0):v))}function la(a){a.u=!1;a.c.x||a.c.y?!a.c.x&&0<a.c.y?a.i=[u[0]]:!a.c.x&&0>a.c.y?a.i=[u[1]]:0<a.c.x&&!a.c.y?a.i=
[u[3]]:0>a.c.x&&!a.c.y?a.i=[u[2]]:0<a.c.x&&0<a.c.y?a.i=[u[0],u[3]]:0<a.c.x&&0>a.c.y?a.i=[u[1],u[3]]:0>a.c.x&&0<a.c.y?a.i=[u[0],u[2]]:0>a.c.x&&0>a.c.y&&(a.i=[u[1],u[2]]):a.i=[function(a){return a.h.x+a.h.y}]}function X(){for(var a=0;a<b.length;a++)la(b[a])}function r(a){return!isNaN(parseFloat(a))&&isFinite(a)}function ma(){na.clearRect(0,0,D.width,D.height);na.drawImage(Y[T-1],0,0,D.width,D.height)}function fa(a){a.style.opacity=1;a.style.transform="scale(1, 1)"}function oa(a){a.style.opacity=0;a.style.transform=
"scale(0, 0)"}function ea(){var a=0<q-window.innerHeight,c=0<p-window.innerWidth,n=0!==window.screenX-Z,d=0!==window.screenY-aa;K&&b[f]&&(pa++,C.clearRect(0,0,L.width,L.height),C.beginPath(),C.save(),C.translate(64,64),C.rotate(pa*Math.PI/180),C.drawImage(b[f].s,-40,-40,80,80),C.restore(),C.closePath());g.clearRect(0,0,p,q);for(var e=0;e<b.length&&(a||c||n||d);e++)n&&(b[e].b.x+=(window.screenX-Z)/20),d&&(b[e].b.y+=(window.screenY-aa)/20),a&&(b[e].position.y>=window.innerHeight-b[e].r?b[e].b.y-=(q-
window.innerHeight-(q-(b[e].position.y+b[e].r)))/5:b[e].position.y<=b[e].r&&(b[e].b.y+=(q-window.innerHeight-(0-b[e].position.y-b[e].r))/5)),c&&(b[e].position.x>=window.innerWidth-b[e].r?b[e].b.x-=(p-window.innerWidth-(p-(b[e].position.x+b[e].r)))/5:b[e].position.x<=b[e].r&&(b[e].b.x+=(p-window.innerWidth-(0-b[e].position.x-b[e].r))/5));p=M.width=window.innerWidth;q=M.height=window.innerHeight;Z=window.screenX;aa=window.screenY;for(e=0;e<b.length;e++)b[e].P=!1;for(e=0;e<b.length;e++){if(b[e].G)try{b[e].G()}catch(sa){console.error("Your function is wrong! "+
sa.message)}for(a=e+1;a<b.length;a++)k.ca(b[e],b[a]);k.aa(b[e]).$(b[e]).ba(b[e]);b[e].B&&b[e].position.add(b[e].b);b[e].M()}for(e=0;e<l.length;e++)for(l[e].M(),a=0;a<b.length;a++)k.ha(l[e],b[a]);ba&&b.length&&(g.beginPath(),g.fillStyle="#000",g.textAlign="center",g.font="Bold 15px Verdana",g.fillText("r: "+b[f].r+" m: "+b[f].l+" x: "+b[f].position.x.toFixed(1)+" y: "+b[f].position.y.toFixed(1)+" xv: "+b[f].b.x.toFixed(1)+" yv: "+b[f].b.y.toFixed(1),p/2,20),g.closePath());va(ea)}for(var M=h("canvas"),
g=M.getContext("2d"),L=h("skin"),C=L.getContext("2d"),D=h("texture"),na=D.getContext("2d"),p=M.width=window.innerWidth,q=M.height=window.innerHeight,b=[],l=[],f=0,T=4,pa=0,K=!1,ba=!1,v=15,y,z,ca,da,qa,w=[],Y=[],Z=window.screenX,aa=window.screenY,W=!1,N=0,H=5,I=32,J=32,F=R(-5,10),P=R(-5,10),G=R(-5,10),Q=R(-5,10),u=[function(a){return a.position.y>=q-a.r-1},function(a){return a.position.y<=a.r+1},function(a){return a.position.x<=a.r+1},function(a){return a.position.x>=p-a.r-1}],k={c:new m(0,.4),h:new m(.08,
.08),o:.95,F:.97,check:function(a,c,b,d,e){b&&(a.b[c]*=-1,a.position[c]=d,this.R(a),this.da(e,a),Math.abs(a.b[c])<Math.abs(a.c[c])&&!a.u&&(a.b[c]=a.c[c]))},ba:function(a){this.check(a,"x",a.position.x>=p-a.r,p-a.r,1);this.check(a,"x",a.position.x<=a.r,a.r,3);this.check(a,"y",a.position.y>=q-a.r,q-a.r,0);this.check(a,"y",a.position.y<=a.r,a.r,2);if(a.u){var c=Math.abs((a.c.x+a.c.y)/2+(a.h.x+a.h.y)/2);a.b.x=Math.abs(a.b.x)<=c?0:a.b.x;a.b.y=Math.abs(a.b.y)<=c?0:a.b.y}return this},$:function(a){if(a.A){if(a.P)var c=
!0;else{a:{for(c=0;c<a.i.length;c++)if(a.i[c]&&a.i[c](a)){c=!0;break a}c=!1}c=+c}a.u=c}a.u||a.b.add(a.c);return this},aa:function(a){a.b.add(new m((0>a.b.x?1:-1)*a.h.x,(0>a.b.y?1:-1)*a.h.y));return this},da:function(a,c){a&&2!==a?0<c.b.y?c.b.add(new m(0,-c.h.y)):c.b.add(new m(0,c.h.y)):0<c.b.x?c.b.add(new m(-c.h.x,0)):c.b.add(new m(c.h.x,0));return this},W:function(a,c){var b=c.position.x-a.position.x,d=c.position.y-a.position.y;if(0<=(a.b.x-c.b.x)*b+(a.b.y-c.b.y)*d){var e=function(){c.u&&(a.P=!0);
a.u&&(c.P=!0)};b=-Math.atan2(d,b);d=a.l;var f=c.l,g=this.rotate(a.b,b),h=this.rotate(c.b,b),k=new m(c.position.x-a.position.x,c.position.y-a.position.y),l=new m(a.r,0);v1={x:g.x*(d-f)/(d+f)+2*h.x*f/(d+f),y:g.y};v2={x:h.x*(f-d)/(d+f)+2*g.x*d/(d+f),y:h.y};vFinal1=this.rotate(v1,-b);vFinal2=this.rotate(v2,-b);a.c.x||c.c.x?a.c.y||c.c.y?.3490658503988659<Math.abs(k.cos(l))&&.8726646259971648>Math.abs(k.cos(l))&&e():.6981317007977318<Math.abs(k.cos(l))&&e():.6981317007977318>Math.abs(k.cos(l))&&e();a.b.x=
this.F*vFinal1.x;a.b.y=this.F*vFinal1.y;c.b.x=this.F*vFinal2.x;c.b.y=this.F*vFinal2.y}return this},rotate:function(a,b){return{x:a.x*Math.cos(b)-a.y*Math.sin(b),y:a.x*Math.sin(b)+a.y*Math.cos(b)}},ca:function(a,b){B(a.position.x,a.position.y,b.position.x,b.position.y)<=a.r+b.r&&this.W(a,b);return this},j:function(a,b){var c=b.position.x-Math.max(a.x,Math.min(b.position.x,a.x+a.g)),d=b.position.y-Math.max(a.y,Math.min(b.position.y,a.y+a.f));return c*c+d*d<b.r*b.r},ha:function(a,b){if(a.ga)for(var c=
0;c<a.a.length;c++)if(this.j(a.a[c],b)){~b.i.indexOf(a.w.C)||b.i.push(a.w.C);if(!c||2===c||6===c||7===c)this.W({position:new m(a.a[c].x+a.a[c].g/2,a.a[c].y+a.a[c].f/2),b:new m(-b.b.x/1.5,-b.b.y/1.5),l:b.l},b);else if(1===c||4===c)b.b.y*=-1,this.R(b);else if(3===c||5===c)b.b.x*=-1,this.R(b);b.A&&(b.position.x+=2*(b.position.x-(a.a[c].x+a.a[c].g/2))/B(b.position.x,b.position.y,a.a[c].x+a.a[c].g/2,a.a[c].y+a.a[c].f/2),b.position.y+=2*(b.position.y-(a.a[c].y+a.a[c].f/2))/B(b.position.x,b.position.y,a.a[c].x+
a.a[c].g/2,a.a[c].y+a.a[c].f/2))}return this},R:function(a){a.b.ea(a.o);return this}},A={x:p/2-250,y:q/2-50,g:500,f:50,color:"#000000"},d={r:h("r"),l:h("mass"),x:h("x"),y:h("y"),T:h("xspeed"),U:h("yspeed"),c:h("gravity"),h:h("deceleration"),o:h("loss"),Z:h("you"),V:h("balls"),X:h("settings"),D:h("chgimg"),H:h("acspeed"),J:h("blw"),I:h("blh"),Y:h("txtr"),fa:h("phys"),N:h("fvx"),K:h("bvx"),O:h("fvy"),L:h("bvy"),G:h("lawOfMotion"),ia:h("rnd")},U=document.getElementsByClassName("forAll"),ka=["img","r",
"mass",{v:"position",m:"x"},{v:"position",m:"y"},{v:"velocity",m:"x"},{v:"velocity",m:"y"},{v:"gravity",m:"x",S:"y"},{v:"deceleration",m:"x",S:"y"},"loss","lawOfMotion"],t=0;t<U.length;t++)U[t].onclick=ta(t);d.ia.onclick=function(){d.G.value="if (!(Math.round(performance.now()/1000)%2)) {this.velocity.x+=Math.random()*getRandomInt(-10, 10);this.velocity.y+=Math.random()*getRandomInt(-10, 10);function getRandomInt(min, max){return Math.floor(Math.random()*(max-min))+min;}}"};d.Z.oninput=function(){f=
0>+this.value?(this.value=0,0):+this.value>b.length-1?(this.value=b.length-1,b.length-1):+this.value;S()};d.D.oninput=function(){b[f]&&r(parseFloat(this.value))&&(b[f].s=w[0>+this.value?(this.value=0,0):+this.value>w.length-1?(this.value=w.length-1,w.length-1):+this.value])};d.Y.oninput=function(){T=1>+this.value?(this.value=1,1):193<+this.value?(this.value=193,193):+this.value;ma()};L.width=L.height=D.width=D.height=120;for(t=0;79>=t;t++){var E=new Image;E.src="resources/balls/ball"+t+".png";E.onload=
ha;w.push(E)}for(t=1;193>=t;t++)E=new Image,E.src="resources/blocks/block ("+t+").png",E.onload=ha,Y.push(E);for(t=0;t<v;t++)O();ia.prototype.M=function(){this.B&&(this.angle+=this.b.x+this.b.y);g.beginPath();g.save();g.translate(this.position.x,this.position.y);g.rotate(this.angle*Math.PI/180);g.drawImage(this.s,-this.r,-this.r,2*this.r,2*this.r);g.restore();g.closePath()};m.prototype.length=function(){return Math.pow(Math.pow(this.x,2)+Math.pow(this.y,2),.5)};m.prototype.cos=function(a){return(this.x*
a.x+this.y*a.y)/(this.length()*a.length())};m.prototype.add=function(a){this.x+=a.x;this.y+=a.y};m.prototype.ea=function(a){this.x*=a;this.y*=a};m.prototype.toString=function(){return this.x+";"+this.y};x.i=[];x.prototype.M=function(){g.beginPath();g.drawImage(this.s,this.x,this.y,this.g,this.f);g.closePath()};x.prototype.update=function(){var a=.1*this.g,b=.1*this.f,d=.5*this.f;this.a=[{x:this.x,y:this.y,g:a,f:b},{x:this.x+a,y:this.y,g:8*a,f:d},{x:this.x+9*a,y:this.y,g:a,f:b},{x:this.x,y:this.y+
b,g:a,f:8*b},{x:this.x+a,y:this.y+d,g:8*a,f:d},{x:this.x+9*a,y:this.y+b,g:a,f:8*b},{x:this.x,y:this.y+9*b,g:a,f:b},{x:this.x+9*a,y:this.y+9*b,g:a,f:b}]};h("ok").onclick=function(){oa(h("guide"))};document.addEventListener("mousemove",function(a){y=a.clientX;z=a.clientY});document.oncontextmenu=function(){return!1};document.onmousedown=function(a){if(1===a.which){var c=!1;ca=a.clientX;da=a.clientY;for(var d=0;d<b.length;d++)if(B(b[d].position.x,b[d].position.y,y,z)<=b[d].r){c=b[f];b[f]=b[d];b[d]=c;
c=!0;b[f].u=!1;b[f].A=!1;b[f].B=!1;var g=a.clientX-b[f].position.x,e=a.clientY-b[f].position.y;S();break}c&&(this.onmousemove=function(a){var c=b[f],d=a.clientX;a=a.clientY;qa=new m(d-ca,a-da);c.position=new m(d-g,a-e);c.b=qa;ca=d;da=a},this.onmouseup=function(){this.onmouseup=this.onmousemove=null;b[f].A=!0;b[f].B=!0})}else for(d=0;d<b.length;d++)if(B(b[d].position.x,b[d].position.y,y,z)<=b[d].r){c=b[f];b[f]=b[d];b[d]=c;3===a.which?b[f].c=new m(0,0):b[f].h=new m(0,0);S();break}};document.addEventListener("wheel",
function(a){for(var c=0;c<b.length;c++)B(b[c].position.x,b[c].position.y,y,z)<=b[c].r&&(b[c].r+=0>a.deltaY?-1:1,b[c].l+=0>a.deltaY?-1:1)});document.addEventListener("keypress",function(a){function c(a){a.b=new m(a.b.x+H*(y-a.position.x)/B(a.position.x,a.position.y,y,z),a.b.y+H*(z-a.position.y)/B(a.position.x,a.position.y,y,z))}a=a.key;if(a.match(/^[e\u0423]$/i))for(b=[],a=1;a<=v;a++)O();else if(a.match(/^[+=]$/i)&&!K)v++,O(y,z);else if(a.match(/^[-_]$/i)&&!K)b.length&&(v--,b.pop());else if(a.match(/^[\u0451`~]$/i))b.length&&
((K=!K)?(ma(),fa(d.X),S()):(oa(d.X),ua()));else if(a.match(/^[\u0439q]$/i))for(a=0;a<b.length;a++)c(b[a]),b[a].u=!1;else if(a.match(/^[\u0446w]$/i))c(b[f]);else if(a.match(/^[}\]\u044a]$/i))a=new x(y-I/2,z-J/2,I,J,Y[T-1]),a.update(),l.push(a);else if(a.match(/^[{\[\u0445]$/i)&&l.length){var g={position:new m(y,z),r:1},h=!1;for(a=0;a<l.length;a++)if(k.j(l[a],g)){x.i.splice(x.i.indexOf(l[a].w),1);l.splice(a,1);X();h=!h;break}h||(x.i.splice(x.i.indexOf(l[l.length-1].w),1),l.pop(),X())}else if(a.match(/^[p\u0437]$/i))for(a=
0;a<l.length;a++)l[a].x=Math.round(l[a].x/l[a].g)*l[a].g,l[a].y=Math.round(l[a].y/l[a].f)*l[a].f,l[a].update();else a.match(/^[r\u043a]$/i)&&(ba=!ba)});var va=requestAnimationFrame||mozRequestAnimationFrame||webkitRequestAnimationFrame||oRequestAnimationFrame||msRequestAnimationFrame;V=setInterval(V,100);setInterval(X,6E4)});
