window.addEventListener("load",function(){function ea(){N++;273===N&&(V=!V);g.clearRect(0,0,p,q);g.beginPath();g.lineWidth=4;g.strokeStyle=A.color;g.stroke();g.strokeRect(A.x-g.lineWidth/2,A.y-g.lineWidth/2,A.w+g.lineWidth,A.h+g.lineWidth);g.fillStyle="rgb(255, 161, 0)";g.fillRect(A.x,A.y,N/273*A.w,A.h);g.fillStyle="rgb(255, 161, 0)";g.textAlign="center";g.font="normal 25px Verdana";g.fillText("\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430: "+(100*N/273).toFixed(3)+"%",p/2,q/2+30+g.lineWidth);
g.closePath()}function O(){for(var a=15*Math.random()+10^0,c=new m(r(arguments[0])?arguments[0]:Math.random()*p,r(arguments[1])?arguments[1]:Math.random()*q),n="0123456789abcdef".split(""),d="#",e=1;6>=e;e++)d+=n[Math.random()*n.length^0];a=new fa(c,a,d,new m(Math.random()*(P-F)+F,Math.random()*(Q-G)+G),a);arguments.length?b.push(a):b.push(ra(a))}function R(a,c){return Math.floor(Math.random()*(c-a))+a}function ra(a){for(var c=0;c<b.length;c++)a!==b[c]&&B(a.position.x,a.position.y,b[c].position.x,
b[c].position.y)<a.r+b[c].r&&(a.position.x=Math.random()*p,a.position.r=Math.random()*q);return a}function fa(a,c,b,d,e){this.position=a;this.r=c;this.color=b;this.velocity=d;this.mass=e;this.gravity=new m(k.gravity.x,k.gravity.y);this.handlers=[u[0]];this.deceleration=new m(k.deceleration.x,k.deceleration.y);this.loss=k.loss;this.canCallHand=!0;this.angle=0;this.canMove=!0;this.img=w[Math.random()*w.length^0]}function m(a,c){this.x=a;this.y=c}function x(a,c,b,f,e){this.x=a;this.y=c;this.w=b;this.h=
f;this.img=e;this.physical=d.phys.checked;a=this.handler={block:this,checkCollision:function(a){if(!a.gravity.x&&0<a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[1].x,y:this.block.parts[1].y-2,w:this.block.parts[1].w,h:this.block.parts[1].h},a);if(!a.gravity.x&&0>a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[4].x,y:this.block.parts[4].y,w:this.block.parts[4].w,h:this.block.parts[4].h+2},a);if(0<a.gravity.x&&!a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[3].x-
2,y:this.block.parts[3].y,w:this.block.parts[3].w,h:this.block.parts[3].h},a);if(0>a.gravity.x&&!a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[5].x,y:this.block.parts[5].y,w:this.block.parts[5].w+2,h:this.block.parts[5].h},a);if(0<a.gravity.x&&0<a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[1].x,y:this.block.parts[1].y-2,w:this.block.parts[1].w,h:this.block.parts[1].h},a)||k.collisionDetWithBlock({x:this.block.parts[3].x-2,y:this.block.parts[3].y,w:this.block.parts[3].w,
h:this.block.parts[3].h},a);if(0<a.gravity.x&&0>a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[4].x,y:this.block.parts[4].y,w:this.block.parts[4].w,h:this.block.parts[4].h+2},a)||k.collisionDetWithBlock({x:this.block.parts[3].x-2,y:this.block.parts[3].y,w:this.block.parts[3].w,h:this.block.parts[3].h},a);if(0>a.gravity.x&&0<a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[5].x,y:this.block.parts[5].y,w:this.block.parts[5].w+2,h:this.block.parts[5].h},a)||k.collisionDetWithBlock({x:this.block.parts[1].x,
y:this.block.parts[1].y-2,w:this.block.parts[1].w,h:this.block.parts[1].h},a);if(0>a.gravity.x&&0>a.gravity.y)return k.collisionDetWithBlock({x:this.block.parts[5].x,y:this.block.parts[5].y,w:this.block.parts[5].w+2,h:this.block.parts[5].h},a)||k.collisionDetWithBlock({x:this.block.parts[4].x,y:this.block.parts[4].y,w:this.block.parts[4].w,h:this.block.parts[4].h+2},a)}};a.checkCollision=a.checkCollision.bind(a);(x.handlers?x.handlers:[]).push(a)}function ta(a){return function(){var c=[r(+d.chgimg.value)?
w[+d.chgimg.value]:b[f].img?b[f].img:w[Math.random()*w.length^0],r(parseFloat(d.r.value))?+d.r.value:100*Math.random()^0,r(parseFloat(d.mass.value))?+d.mass.value:100*Math.random()^0,{sp:r(parseFloat(d.x.value))?+d.x.value:Math.random()*p^0},{sp:r(parseFloat(d.y.value))?+d.y.value:Math.random()*q^0},{sp:r(parseFloat(d.xspeed.value))?+d.xspeed.value:20*Math.random()^0},{sp:r(parseFloat(d.yspeed.value))?+d.yspeed.value:20*Math.random()^0},{sp:r(+d.gravity.value.match(/[\d.-]+/)[0])?+d.gravity.value.match(/[\d.-]+/)[0]:
k.gravity.x,tp:r(+d.gravity.value.match(/[\d.-]+/g)[1])?+d.gravity.value.match(/[\d.-]+/g)[1]:k.gravity.y},{sp:r(+d.deceleration.value.match(/[\d.-]+/)[0])?+d.deceleration.value.match(/[\d.-]+/)[0]:k.deceleration.x,tp:r(+d.deceleration.value.match(/[\d.-]+/g)[1])?+d.deceleration.value.match(/[\d.-]+/g)[1]:k.deceleration.y},r(parseFloat(d.loss.value))?+d.loss.value:k.loss,new Function("",d.lawOfMotion.value)];if(arguments.length)for(var n=0;n<b.length;n++)ha(b[n],ia[a],c[a]);else ha(b[f],ia[a],c[a])}}
function ha(a,c,b){if("string"===typeof c)a[c]=b;else for(var n in c)"fp"!=n&&(a[c.fp][c[n]]=b[n],"deceleration"===c.fp&&("sp"===n?k.deceleration.x=b[n]:k.deceleration.y=b[n]),"gravity"===c.fp&&("sp"===n?k.gravity.x=b[n]:k.gravity.y=b[n],ja(a)))}function B(a,c,b,d){return Math.pow(Math.pow(a-b,2)+Math.pow(c-d,2),.5)}function h(a){return document.getElementById(a)}function S(){d.you.value=f;d.chgimg.value=w.indexOf(b[f].img);d.r.value=+b[f].r.toFixed(3);d.mass.value=+b[f].mass.toFixed(3);d.x.value=
+b[f].position.x.toFixed(3);d.y.value=+b[f].position.y.toFixed(3);d.xspeed.value=+b[f].velocity.x.toFixed(3);d.yspeed.value=+b[f].velocity.y.toFixed(3);d.gravity.value=b[f].gravity;d.deceleration.value=b[f].deceleration;d.loss.value=b[f].loss;d.balls.value=v;d.acspeed.value=H;d.blw.value=I;d.blh.value=J;d.txtr.value=T;d.fvx.value=F;d.bvx.value=P;d.fvy.value=G;d.bvy.value=Q}function ua(){for(var a=1;a<U.length;a++)U[a].onclick();H=parseFloat(+d.acspeed.value)?+d.acspeed.value:H;v=+d.balls.value;I=
parseFloat(+d.blw.value)?d.blw.value:I;J=parseFloat(+d.blh.value)?d.blh.value:J;F="number"==typeof parseFloat(+d.fvx.value)?+d.fvx.value:F;P="number"==typeof parseFloat(+d.bvx.value)?+d.bvx.value:P;G="number"==typeof parseFloat(+d.fvy.value)?+d.fvy.value:G;Q="number"==typeof parseFloat(+d.bvy.value)?+d.bvy.value:Q;if(v>b.length)for(a=b.length;a<v;a++)O();else v<b.length&&(b=b.slice(0,0>v?(v=0,0):v))}function ja(a){a.onGround=!1;a.gravity.x||a.gravity.y?!a.gravity.x&&0<a.gravity.y?a.handlers=[u[0]]:
!a.gravity.x&&0>a.gravity.y?a.handlers=[u[1]]:0<a.gravity.x&&!a.gravity.y?a.handlers=[u[3]]:0>a.gravity.x&&!a.gravity.y?a.handlers=[u[2]]:0<a.gravity.x&&0<a.gravity.y?a.handlers=[u[0],u[3]]:0<a.gravity.x&&0>a.gravity.y?a.handlers=[u[1],u[3]]:0>a.gravity.x&&0<a.gravity.y?a.handlers=[u[0],u[2]]:0>a.gravity.x&&0>a.gravity.y&&(a.handlers=[u[1],u[2]]):a.handlers=[function(a){return a.deceleration.x+a.deceleration.y}]}function W(){for(var a=0;a<b.length;a++)ja(b[a])}function r(a){return!isNaN(parseFloat(a))&&
isFinite(a)}function ka(){la.clearRect(0,0,D.width,D.height);la.drawImage(X[T-1],0,0,D.width,D.height)}function ma(a){a.style.opacity=1;a.style.transform="scale(1, 1)"}function na(a){a.style.opacity=0;a.style.transform="scale(0, 0)"}function oa(){var a=0<q-window.innerHeight,c=0<p-window.innerWidth,n=0!==window.screenX-Y,d=0!==window.screenY-Z;K&&b[f]&&(pa++,C.clearRect(0,0,L.width,L.height),C.beginPath(),C.save(),C.translate(64,64),C.rotate(pa*Math.PI/180),C.drawImage(b[f].img,-40,-40,80,80),C.restore(),
C.closePath());g.clearRect(0,0,p,q);for(var e=0;e<b.length&&(a||c||n||d);e++)n&&(b[e].velocity.x+=(window.screenX-Y)/20),d&&(b[e].velocity.y+=(window.screenY-Z)/20),a&&(b[e].position.y>=window.innerHeight-b[e].r?b[e].velocity.y-=(q-window.innerHeight-(q-(b[e].position.y+b[e].r)))/5:b[e].position.y<=b[e].r&&(b[e].velocity.y+=(q-window.innerHeight-(0-b[e].position.y-b[e].r))/5)),c&&(b[e].position.x>=window.innerWidth-b[e].r?b[e].velocity.x-=(p-window.innerWidth-(p-(b[e].position.x+b[e].r)))/5:b[e].position.x<=
b[e].r&&(b[e].velocity.x+=(p-window.innerWidth-(0-b[e].position.x-b[e].r))/5));p=M.width=window.innerWidth;q=M.height=window.innerHeight;Y=window.screenX;Z=window.screenY;for(e=0;e<b.length;e++)b[e].isCollided=!1;for(e=0;e<b.length;e++){if(b[e].lawOfMotion)try{b[e].lawOfMotion()}catch(sa){console.error("Your function is wrong! "+sa.message)}for(a=e+1;a<b.length;a++)k.collisionWithBall(b[e],b[a]);k.airResistance(b[e]).addGravity(b[e]).checkCoords(b[e]);b[e].canMove&&b[e].position.add(b[e].velocity);
b[e].draw()}for(e=0;e<l.length;e++)for(l[e].draw(),a=0;a<b.length;a++)k.resolveCollisionWithBlock(l[e],b[a]);aa&&b.length&&(g.beginPath(),g.fillStyle="#000",g.textAlign="center",g.font="Bold 15px Verdana",g.fillText("r: "+b[f].r+" m: "+b[f].mass+" x: "+b[f].position.x.toFixed(1)+" y: "+b[f].position.y.toFixed(1)+" xv: "+b[f].velocity.x.toFixed(1)+" yv: "+b[f].velocity.y.toFixed(1),p/2,20),g.closePath());va(oa)}for(var M=h("canvas"),g=M.getContext("2d"),L=h("skin"),C=L.getContext("2d"),D=h("texture"),
la=D.getContext("2d"),p=M.width=window.innerWidth,q=M.height=window.innerHeight,b=[],l=[],f=0,T=4,pa=0,K=!1,aa=!1,v=15,y,z,ba,ca,qa,w=[],X=[],Y=window.screenX,Z=window.screenY,V=!1,N=0,H=5,I=32,J=32,F=R(-5,10),P=R(-5,10),G=R(-5,10),Q=R(-5,10),u=[function(a){return a.position.y>=q-a.r-1},function(a){return a.position.y<=a.r+1},function(a){return a.position.x<=a.r+1},function(a){return a.position.x>=p-a.r-1}],k={gravity:new m(0,.4),deceleration:new m(.08,.08),loss:.95,collisionLoss:.97,check:function(a,
c,b,d,e){b&&(a.velocity[c]*=-1,a.position[c]=d,this.lose(a),this.groundResistance(e,a),Math.abs(a.velocity[c])<Math.abs(a.gravity[c])&&!a.onGround&&(a.velocity[c]=a.gravity[c]))},checkCoords:function(a){this.check(a,"x",a.position.x>=p-a.r,p-a.r,1);this.check(a,"x",a.position.x<=a.r,a.r,3);this.check(a,"y",a.position.y>=q-a.r,q-a.r,0);this.check(a,"y",a.position.y<=a.r,a.r,2);if(a.onGround){var c=Math.abs((a.gravity.x+a.gravity.y)/2+(a.deceleration.x+a.deceleration.y)/2);a.velocity.x=Math.abs(a.velocity.x)<=
c?0:a.velocity.x;a.velocity.y=Math.abs(a.velocity.y)<=c?0:a.velocity.y}return this},addGravity:function(a){if(a.canCallHand)if(a.isCollided)a.onGround=!0;else{var c;a:{for(c=0;c<a.handlers.length;c++)if(a.handlers[c]&&a.handlers[c](a)){c=!0;break a}c=!1}a.onGround=+c}a.onGround||a.velocity.add(a.gravity);return this},airResistance:function(a){a.velocity.add(new m((0>a.velocity.x?1:-1)*a.deceleration.x,(0>a.velocity.y?1:-1)*a.deceleration.y));return this},groundResistance:function(a,c){a&&2!==a?0<
c.velocity.y?c.velocity.add(new m(0,-c.deceleration.y)):c.velocity.add(new m(0,c.deceleration.y)):0<c.velocity.x?c.velocity.add(new m(-c.deceleration.x,0)):c.velocity.add(new m(c.deceleration.x,0));return this},resolveCollision:function(a,c){var b=c.position.x-a.position.x,d=c.position.y-a.position.y;if(0<=(a.velocity.x-c.velocity.x)*b+(a.velocity.y-c.velocity.y)*d){var e=function(){c.onGround&&(a.isCollided=!0);a.onGround&&(c.isCollided=!0)};b=-Math.atan2(d,b);d=a.mass;var f=c.mass,g=this.rotate(a.velocity,
b),k=this.rotate(c.velocity,b),h=new m(c.position.x-a.position.x,c.position.y-a.position.y),l=new m(a.r,0);v1={x:g.x*(d-f)/(d+f)+2*k.x*f/(d+f),y:g.y};v2={x:k.x*(f-d)/(d+f)+2*g.x*d/(d+f),y:k.y};vFinal1=this.rotate(v1,-b);vFinal2=this.rotate(v2,-b);a.gravity.x||c.gravity.x?a.gravity.y||c.gravity.y?.3490658503988659<Math.abs(h.cos(l))&&.8726646259971648>Math.abs(h.cos(l))&&e():.6981317007977318<Math.abs(h.cos(l))&&e():.6981317007977318>Math.abs(h.cos(l))&&e();a.velocity.x=this.collisionLoss*vFinal1.x;
a.velocity.y=this.collisionLoss*vFinal1.y;c.velocity.x=this.collisionLoss*vFinal2.x;c.velocity.y=this.collisionLoss*vFinal2.y}return this},rotate:function(a,b){return{x:a.x*Math.cos(b)-a.y*Math.sin(b),y:a.x*Math.sin(b)+a.y*Math.cos(b)}},collisionWithBall:function(a,b){B(a.position.x,a.position.y,b.position.x,b.position.y)<=a.r+b.r&&this.resolveCollision(a,b);return this},collisionDetWithBlock:function(a,b){var c=b.position.x-Math.max(a.x,Math.min(b.position.x,a.x+a.w)),d=b.position.y-Math.max(a.y,
Math.min(b.position.y,a.y+a.h));return c*c+d*d<b.r*b.r},resolveCollisionWithBlock:function(a,b){if(a.physical)for(var c=0;c<a.parts.length;c++)if(this.collisionDetWithBlock(a.parts[c],b)){~b.handlers.indexOf(a.handler.checkCollision)||b.handlers.push(a.handler.checkCollision);if(!c||2===c||6===c||7===c)this.resolveCollision({position:new m(a.parts[c].x+a.parts[c].w/2,a.parts[c].y+a.parts[c].h/2),velocity:new m(-b.velocity.x/1.5,-b.velocity.y/1.5),mass:b.mass},b);else if(1===c||4===c)b.velocity.y*=
-1,this.lose(b);else if(3===c||5===c)b.velocity.x*=-1,this.lose(b);b.canCallHand&&(b.position.x+=2*(b.position.x-(a.parts[c].x+a.parts[c].w/2))/B(b.position.x,b.position.y,a.parts[c].x+a.parts[c].w/2,a.parts[c].y+a.parts[c].h/2),b.position.y+=2*(b.position.y-(a.parts[c].y+a.parts[c].h/2))/B(b.position.x,b.position.y,a.parts[c].x+a.parts[c].w/2,a.parts[c].y+a.parts[c].h/2))}return this},lose:function(a){a.velocity.mult(a.loss);return this}},A={x:p/2-250,y:q/2-50,w:500,h:50,color:"#000000"},d={r:h("r"),
mass:h("mass"),x:h("x"),y:h("y"),xspeed:h("xspeed"),yspeed:h("yspeed"),gravity:h("gravity"),deceleration:h("deceleration"),loss:h("loss"),you:h("you"),balls:h("balls"),settings:h("settings"),chgimg:h("chgimg"),acspeed:h("acspeed"),blw:h("blw"),blh:h("blh"),txtr:h("txtr"),phys:h("phys"),fvx:h("fvx"),bvx:h("bvx"),fvy:h("fvy"),bvy:h("bvy"),lawOfMotion:h("lawOfMotion"),rnd:h("rnd")},U=document.getElementsByClassName("forAll"),ia=["img","r","mass",{fp:"position",sp:"x"},{fp:"position",sp:"y"},{fp:"velocity",
sp:"x"},{fp:"velocity",sp:"y"},{fp:"gravity",sp:"x",tp:"y"},{fp:"deceleration",sp:"x",tp:"y"},"loss","lawOfMotion"],t=0;t<U.length;t++)U[t].onclick=ta(t);d.rnd.onclick=function(){d.lawOfMotion.value="if (!(Math.round(performance.now()/1000)%2)) {this.velocity.x+=Math.random()*getRandomInt(-10, 10);this.velocity.y+=Math.random()*getRandomInt(-10, 10);function getRandomInt(min, max){return Math.floor(Math.random()*(max-min))+min;}}"};d.you.oninput=function(){f=0>+this.value?(this.value=0,0):+this.value>
b.length-1?(this.value=b.length-1,b.length-1):+this.value;S()};d.chgimg.oninput=function(){b[f]&&r(parseFloat(this.value))&&(b[f].img=w[0>+this.value?(this.value=0,0):+this.value>w.length-1?(this.value=w.length-1,w.length-1):+this.value])};d.txtr.oninput=function(){T=1>+this.value?(this.value=1,1):193<+this.value?(this.value=193,193):+this.value;ka()};L.width=L.height=D.width=D.height=120;for(t=0;79>=t;t++){var E=new Image;E.src="resources/balls/ball"+t+".png";E.onload=ea;w.push(E)}for(t=1;193>=t;t++)E=
new Image,E.src="resources/blocks/block ("+t+").png",E.onload=ea,X.push(E);for(t=0;t<v;t++)O();fa.prototype.draw=function(){this.canMove&&(this.angle+=this.velocity.x+this.velocity.y);g.beginPath();g.save();g.translate(this.position.x,this.position.y);g.rotate(this.angle*Math.PI/180);g.drawImage(this.img,-this.r,-this.r,2*this.r,2*this.r);g.restore();g.closePath()};m.prototype.length=function(){return Math.pow(Math.pow(this.x,2)+Math.pow(this.y,2),.5)};m.prototype.cos=function(a){return(this.x*a.x+
this.y*a.y)/(this.length()*a.length())};m.prototype.add=function(a){this.x+=a.x;this.y+=a.y};m.prototype.mult=function(a){this.x*=a;this.y*=a};m.prototype.toString=function(){return this.x+";"+this.y};x.handlers=[];x.prototype.draw=function(){g.beginPath();g.drawImage(this.img,this.x,this.y,this.w,this.h);g.closePath()};x.prototype.update=function(){var a=.1*this.w,b=.1*this.h,d=.5*this.h;this.parts=[{x:this.x,y:this.y,w:a,h:b},{x:this.x+a,y:this.y,w:8*a,h:d},{x:this.x+9*a,y:this.y,w:a,h:b},{x:this.x,
y:this.y+b,w:a,h:8*b},{x:this.x+a,y:this.y+d,w:8*a,h:d},{x:this.x+9*a,y:this.y+b,w:a,h:8*b},{x:this.x,y:this.y+9*b,w:a,h:b},{x:this.x+9*a,y:this.y+9*b,w:a,h:b}]};h("ok").onclick=function(){na(h("guide"))};document.addEventListener("mousemove",function(a){y=a.clientX;z=a.clientY});document.oncontextmenu=function(){return!1};document.onmousedown=function(a){if(1===a.which){var c=!1;ba=a.clientX;ca=a.clientY;for(var d=0;d<b.length;d++)if(B(b[d].position.x,b[d].position.y,y,z)<=b[d].r){c=b[f];b[f]=b[d];
b[d]=c;c=!0;b[f].onGround=!1;b[f].canCallHand=!1;b[f].canMove=!1;var g=a.clientX-b[f].position.x,e=a.clientY-b[f].position.y;S();break}c&&(this.onmousemove=function(a){var c=b[f],d=a.clientX;a=a.clientY;qa=new m(d-ba,a-ca);c.position=new m(d-g,a-e);c.velocity=qa;ba=d;ca=a},this.onmouseup=function(){this.onmouseup=this.onmousemove=null;b[f].canCallHand=!0;b[f].canMove=!0})}else for(d=0;d<b.length;d++)if(B(b[d].position.x,b[d].position.y,y,z)<=b[d].r){c=b[f];b[f]=b[d];b[d]=c;3===a.which?b[f].gravity=
new m(0,0):b[f].deceleration=new m(0,0);S();break}};document.addEventListener("wheel",function(a){for(var c=0;c<b.length;c++)B(b[c].position.x,b[c].position.y,y,z)<=b[c].r&&(b[c].r+=0>a.deltaY?-1:1,b[c].mass+=0>a.deltaY?-1:1)});document.addEventListener("keypress",function(a){function c(a){a.velocity=new m(a.velocity.x+H*(y-a.position.x)/B(a.position.x,a.position.y,y,z),a.velocity.y+H*(z-a.position.y)/B(a.position.x,a.position.y,y,z))}a=a.key;if(a.match(/^[e\u0423]$/i))for(b=[],a=1;a<=v;a++)O();else if(a.match(/^[+=]$/i)&&
!K)v++,O(y,z);else if(a.match(/^[-_]$/i)&&!K)b.length&&(v--,b.pop());else if(a.match(/^[\u0451`~]$/i))b.length&&((K=!K)?(ka(),ma(d.settings),S()):(na(d.settings),ua()));else if(a.match(/^[\u0439q]$/i))for(a=0;a<b.length;a++)c(b[a]),b[a].onGround=!1;else if(a.match(/^[\u0446w]$/i))c(b[f]);else if(a.match(/^[}\]\u044a]$/i))a=new x(y-I/2,z-J/2,I,J,X[T-1]),a.update(),l.push(a);else if(a.match(/^[{\[\u0445]$/i)&&l.length){var g={position:new m(y,z),r:1},h=!1;for(a=0;a<l.length;a++)if(k.collisionDetWithBlock(l[a],
g)){x.handlers.splice(x.handlers.indexOf(l[a].handler),1);l.splice(a,1);W();h=!h;break}h||(x.handlers.splice(x.handlers.indexOf(l[l.length-1].handler),1),l.pop(),W())}else if(a.match(/^[p\u0437]$/i))for(a=0;a<l.length;a++)l[a].x=Math.round(l[a].x/l[a].w)*l[a].w,l[a].y=Math.round(l[a].y/l[a].h)*l[a].h,l[a].update();else a.match(/^[r\u043a]$/i)&&(aa=!aa)});var va=requestAnimationFrame||mozRequestAnimationFrame||webkitRequestAnimationFrame||oRequestAnimationFrame||msRequestAnimationFrame,da=function(){V&&
(oa(),ma(h("guide")),clearInterval(da))};da=setInterval(da,100);setInterval(W,6E4)});